// Mappa dei loghi inclusi nell'app: tutti loghi ufficiali reali (recuperati
// da Wikimedia Commons/Wikipedia o forniti direttamente).
const logoMap: { [key: string]: any } = {
  'esselunga.png': require('../assets/loghi/esselunga.png'),
  'coop.png': require('../assets/loghi/coop.png'),
  'conad.png': require('../assets/loghi/conad.png'),
  'eurospin.png': require('../assets/loghi/eurospin.png'),
  'lidl.png': require('../assets/loghi/lidl.png'),
  'despar.png': require('../assets/loghi/despar.png'),
  'todis.png': require('../assets/loghi/todis.png'),
  'pam.png': require('../assets/loghi/pam.png'),
  'iper.png': require('../assets/loghi/iper.png'),
  'famila.png': require('../assets/loghi/famila.png'),
  'penny.png': require('../assets/loghi/penny.png'),
  'auchan.png': require('../assets/loghi/auchan.png'),
  'unes.png': require('../assets/loghi/unes.png'),
  'carrefour.png': require('../assets/loghi/carrefour.png'),
  'bennet.png': require('../assets/loghi/bennet.png'),
  'md.png': require('../assets/loghi/md.png'),
  'sigma.png': require('../assets/loghi/sigma.png'),
  'sisa.png': require('../assets/loghi/sisa.png'),
  'deco.png': require('../assets/loghi/deco.png'),
  'decathlon.png': require('../assets/loghi/decathlon.png'),
  'brico.png': require('../assets/loghi/brico.png'),
  'ikea.png': require('../assets/loghi/ikea.png'),
  'obi.png': require('../assets/loghi/obi.png'),
  'bricofer.png': require('../assets/loghi/bricofer.png'),
  'mediaworld.png': require('../assets/loghi/mediaworld.png'),
  'euronics.png': require('../assets/loghi/euronics.png'),
  'ovs.png': require('../assets/loghi/ovs.png'),
  'terranova.png': require('../assets/loghi/terranova.png'),
  'pinko.png': require('../assets/loghi/pinko.png'),
  'piazza_italia.png': require('../assets/loghi/piazza_italia.png'),
  'alcott.png': require('../assets/loghi/alcott.png'),
  'benetton.png': require('../assets/loghi/benetton.png'),
  'liujo.png': require('../assets/loghi/liujo.png'),
  'twinset.png': require('../assets/loghi/twinset.png'),
  'replay.png': require('../assets/loghi/replay.png'),
  'sisley.png': require('../assets/loghi/sisley.png'),
  'yamamay.png': require('../assets/loghi/yamamay.png'),
  'tezenis.png': require('../assets/loghi/tezenis.png'),
  'carpisa.png': require('../assets/loghi/carpisa.png'),
  'gucci.png': require('../assets/loghi/gucci.png'),
  'prada.png': require('../assets/loghi/prada.png'),
  'armani.png': require('../assets/loghi/armani.png'),
  'versace.png': require('../assets/loghi/versace.png'),
  'dolceegabbana.png': require('../assets/loghi/dolceegabbana.png'),
  'fendi.png': require('../assets/loghi/fendi.png'),
  'bottegaveneta.png': require('../assets/loghi/bottegaveneta.png'),
  'moschino.png': require('../assets/loghi/moschino.png'),
  'miumiu.png': require('../assets/loghi/miumiu.png'),
  'maxmara.png': require('../assets/loghi/maxmara.png'),
  'trussardi.png': require('../assets/loghi/trussardi.png'),
  'loropiana.png': require('../assets/loghi/loropiana.png'),
  'ilgigante.png': require('../assets/loghi/ilgigante.png'),
  'u2.png': require('../assets/loghi/u2.png'),
  'dpiu.png': require('../assets/loghi/dpiu.png'),
  'inss.png': require('../assets/loghi/inss.png'),
  'calliope.png': require('../assets/loghi/calliope.png'),
  'zuiki.png': require('../assets/loghi/zuiki.png'),
  'motivi.png': require('../assets/loghi/motivi.png'),
  'maxeco.png': require('../assets/loghi/maxeco.png'),
  'imperial.png': require('../assets/loghi/imperial.png'),
  'cisalfa.png': require('../assets/loghi/cisalfa.png'),
  'millionstore.jpg': require('../assets/loghi/millionstore.jpg'),
  // Aggiungi qui il logo quando ne hai uno nuovo e corretto in assets/loghi
};

export default logoMap;
